from typing import Optional, Callable, Any
import serial

class SerialManager:
    def __init__(self, port: str, baudrate: int = 115200) -> None: ...
    @property
    def connected(self) -> bool: ...
    @property
    def port(self) -> str: ...
    @property
    def baudrate(self) -> int: ...
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def send_command(self, command: str) -> bool: ...
    def get_last_message(self) -> Optional[str]: ...
    def set_callback(self, callback: Callable[[str], None]) -> None: ... 